language: java

# uses xvfb for running gui tests
# simulates a gui with (X Virtual Framebuffer)
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - gradle assemble
  - gradle -Pheadless=true test

notifications:
  email: false
